[[chapter2]]
== Context Transport Key

The Context Transport Key (CTK) is always stored in the `H` register with the
highest ID --- `H7`, `H15`, or `H31`. The CTK can only be modified in effective
privilege mode M. Attempting to decode an HAC instruction which modifies the
CTK outside of effective privilege mode M results in an exception with code
"Illegal Instruction". A CTK can be loaded using set or import instructions.
The CTK may ignore writes. The CTK register follows the WARL behavior.

[NOTE]
====
Writes may be ignored in the CTK register such that smaller implementations can
hardcode a key.
====

[NOTE]
====
CTK is encoded in an HAC register instead of a CSR because its width is larger
than XLEN.
====

Import and export operations use the currently loaded CTK to import and export
the data in each register. Registers loaded under a CTK X can only be used when
CTK X is loaded. Attempting to use a register with a different CTK Y results in
an exception with code "Illegal Instruction".
